export const GET_ADDRESS = 'GET_ADDRESS'
export const REQUEST_FAIL = 'REQUEST_FAIL'
export const GET_ADDRESS_REQUEST = 'GET_ADDRESS_REQUEST'
export const EDIT_ADDRESS = 'EDIT_ADDRESS'
export const EDIT_ADDRESS_COMPLETE = 'EDIT_ADDRESS_COMPLETE'

